server:
  port: 8090
spring:
  application:
    name: BookManager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://yifanrds.mysql.rds.aliyuncs.com:3306/book_manager
    username: book
    password: Book123@

#mybatisplus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false #将下划线映射成小驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
